# Generated by Django 3.0 on 2021-01-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20, unique=True, verbose_name='中安料号')),
                ('item_name', models.CharField(max_length=32, verbose_name='类别')),
                ('describe', models.CharField(max_length=256, null=True, verbose_name='描述')),
                ('firm_code', models.CharField(max_length=20, verbose_name='厂商型号')),
                ('firm_name', models.CharField(max_length=32, verbose_name='厂商名字')),
                ('material_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='物料照片')),
                ('specification', models.FileField(blank=True, null=True, upload_to='', verbose_name='规格书')),
                ('remark', models.CharField(max_length=256, null=True, verbose_name='备注')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'materialinfo',
            },
        ),
        migrations.CreateModel(
            name='Superclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('description', models.CharField(max_length=72, verbose_name='描述')),
            ],
            options={
                'db_table': 'superclass',
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='编号')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('example', models.CharField(max_length=72, verbose_name='举例')),
                ('superclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.Superclass', verbose_name='父类')),
            ],
            options={
                'db_table': 'subclass',
            },
        ),
    ]
