# Generated by Django 3.0 on 2021-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20210120_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclass',
            name='example',
            field=models.CharField(max_length=72, null=True, verbose_name='举例'),
        ),
    ]
