# Generated by Django 3.0 on 2021-03-08 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0003_auto_20210120_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'ordering': ['superclass', 'code']},
        ),
        migrations.AlterModelOptions(
            name='superclass',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='materialinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='material_img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='物料照片'),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='materialinfo',
            name='specification',
            field=models.FileField(blank=True, null=True, upload_to='specification', verbose_name='规格书'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='superclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Superclass', verbose_name='父类'),
        ),
    ]
